import { Noto_Serif_Georgian } from 'next/font/google'
import "./globals.css";


const serif = Noto_Serif_Georgian({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={serif.className}
      >
        {children}
      </body>
    </html>
  );
}
