import "./globals.css";
import ClientWagmiProvider from "./config";
import { headers } from "next/headers";
import ContextProvider from "./context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookies = headers().get("cookie");
  return (
    <html lang="en">
      <body>
        <ContextProvider cookies={cookies}>{children}</ContextProvider>
      </body>
    </html>
  );
}
